version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - CLUSTER_NAME=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    #ulimits:
    #  memlock:
    #    soft: -1
    #    hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - elasticsearch:host-elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://host-elasticsearch:9200
